version: "3"

services:
  frontend: #리액트 + nginx 서비스명 
    build:
      context: ./Hana_Bridge_FE-Cli
      dockerfile: Dockerfile
    image: hana-frontend
    container_name: hana-frontend-container
    ports:
      - "3000:80"
      - "10052:10050"
    depends_on:
      - backend
      
  backend:
    build: #Spring Boot API 서버 서비스명
      context: ./Hana_Bridge_BE-API
    ports:
      - "8080:8080"
      - "10051:10050"
    image: hana-backend
    container_name: hana-backend-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DATABASE_DB}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      
  redis: #Redis 서비스명
    image: redis:7.2
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_test:/data  # Redis는 /data에 데이터 저장
      
  mysql: #MySQL 서비스명
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
    env_file:
      - .env
    volumes:
      - mysql_test:/var/lib/mysql
      - ./MySQL_init/${INIT_DB_TEST}:/docker-entrypoint-initdb.d/init.sql

volumes:
  #자동으로 프로젝트 폴더명이 앞에 붙음
  #프로젝트폴더명_볼륨명
  #dev 폴더에 있으므로 dev_mysql_test로 생성되는 것
  mysql_test:
  redis_test: