version: "3"

services:
  frontend: #리액트 + nginx 서비스명 
    build:
      context: ./Hana_Bridge_FE-Cli
      dockerfile: Dockerfile
    image: hana-frontend
    container_name: hana-frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
      
  backend:
    build: #Spring Boot API 서버 서비스명
      context: ./Hana_Bridge_BE-API
    ports:
      - "8080:8080"
    image: hana-backend
    container_name: hana-backend-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DATABASE_DB}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      
  redis: #Redis 서비스명
    image: redis:7.2
    container_name: redis-container
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul  # ✅ 시스템 시간대 설정
    volumes:
      - redis_service:/data  # Redis는 /data에 데이터 저장
      
  mysql: #MySQL 서비스명
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - TZ=Asia/Seoul
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    env_file:
      - .env
    command:
      --default-time-zone='Asia/Seoul'
    volumes:
      - mysql_service:/var/lib/mysql
      - ./MySQL_init/${INIT_DB}:/docker-entrypoint-initdb.d/init.sql
      - ./MySQL_init/my.cnf:/etc/mysql/conf.d/my.cnf # 한글 설정

volumes:
  #자동으로 프로젝트 폴더명이 앞에 붙음
  #프로젝트폴더명_볼륨명
  #dev 폴더에 있으므로 dev_mysql_test로 생성되는 것
  mysql_service:
  redis_service: