spring:
  application:
    name: Backend_Monitor

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
