spring:
  config:
    import: optional:file:.env
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_DB}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: ${DATABASE_USERNAME}
    password : ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
openai:
  api-key: ${OPENAI_API_KEY}
  model: ${OPENAI_API_MODEL}
  url: ${OPENAI_API_URL}
  prompts:
    0: ${OPENAI_PROMPT0}
    1: ${OPENAI_PROMPT1}

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRETKEY}